### ISSUE TITLE
Not closing connections

### ISSUE THREAD

**Issue by danlucraft** [bmabey/rosetta_queue#1]
When using the AMQP adapter. If you publish a message from within a receiver, RosettaQueue will open an AMQP connection to send the message but not close the connection, ever.

**Comment by bmabey** [comment]
Sorry, I just saw this message.  I know Chris has redone some of the AMQP stuff (he actually favors the bunny based one now).. do you know if this is still an issue?

**Comment by danlucraft** [comment]
Np. Sorry don't know if it's still an issue. We switched to using tmm1-amqp directly instead (this was at 11pm on the night of Songkick's launch :), ah fun times!)
